export const GET_NEWSLETTER_SUBSCRIBERS_REQUEST = "GET_NEWSLETTER_SUBSCRIBERS_REQUEST";
export const GET_NEWSLETTER_SUBSCRIBERS_SUCCESS = "GET_NEWSLETTER_SUBSCRIBERS_SUCCESS";
export const GET_NEWSLETTER_SUBSCRIBERS_FAIL = "GET_NEWSLETTER_SUBSCRIBERS_FAIL";

export const CLEAR_NEWSLETTER_ERRORS = "CLEAR_NEWSLETTER_ERRORS";

